name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Buildozer
        uses: ArtemShatalov/buildozer-action@v1.2
        with:
          workdir: .
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-quran-app
          path: bin/*.apk
